// ContentView.swift — root SwiftUI view for the scaffold.
//
// The .frame(minWidth:, minHeight:) call is REQUIRED. SwiftUI on macOS opens
// the window at the intrinsic content size of the root view; without an
// explicit frame, a VStack of text can produce a 50×50pt window in the
// top-left of the screen that's easy to mistake for "no window opened".
// Recommended floor 600×400; games and dashboards usually want 800×600+.
// See wisdom rule `mac-002`.

import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack(spacing: 16) {
            Text("<DisplayName>")
                .font(.largeTitle.bold())
            Text("Generated by mChatAI+")
                .foregroundStyle(.secondary)
        }
        .padding(40)
        .frame(minWidth: 800, minHeight: 600)
    }
}

#Preview {
    ContentView()
}
