// BEGIN mchatai-web-components: resources.spanish-phrasebook (resources/SpanishPhrasebook.js)

/**
 * Deep Spanish<->English travel phrasebook: 421 phrases across greetings, dining,
 * directions, hotel, shopping, transport, emergencies, time & numbers. Each item:
 *   { es: Spanish (with accents), en: English (ASCII), category }
 * Drives a language memory-match (pair es<->en via MemoryMatchBoard.buildPairDeck)
 * or flashcards/quiz (prompt=es, answer=en via entities.content-dictionary).
 */
export const SPANISH_PHRASES = [
  { es: "Hola", en: "Hello", category: "greetings" },
  { es: "Buenos días", en: "Good morning", category: "greetings" },
  { es: "Buenas tardes", en: "Good afternoon", category: "greetings" },
  { es: "Buenas noches", en: "Good evening", category: "greetings" },
  { es: "¿Qué tal?", en: "How's it going?", category: "greetings" },
  { es: "¿Cómo estás?", en: "How are you?", category: "greetings" },
  { es: "¿Cómo está usted?", en: "How are you? (formal)", category: "greetings" },
  { es: "Bien, gracias", en: "Fine, thank you", category: "greetings" },
  { es: "Muy bien", en: "Very well", category: "greetings" },
  { es: "¿Y tú?", en: "And you?", category: "greetings" },
  { es: "Encantado", en: "Nice to meet you", category: "introductions" },
  { es: "Mucho gusto", en: "Pleased to meet you", category: "introductions" },
  { es: "Me llamo Ana", en: "My name is Ana", category: "introductions" },
  { es: "¿Cómo te llamas?", en: "What's your name?", category: "introductions" },
  { es: "¿Cómo se llama usted?", en: "What's your name? (formal)", category: "introductions" },
  { es: "Soy de Estados Unidos", en: "I'm from the United States", category: "introductions" },
  { es: "¿De dónde eres?", en: "Where are you from?", category: "introductions" },
  { es: "Este es mi amigo", en: "This is my friend", category: "introductions" },
  { es: "Soy turista", en: "I'm a tourist", category: "introductions" },
  { es: "Sí", en: "Yes", category: "yes/no/please/thank-you" },
  { es: "No", en: "No", category: "yes/no/please/thank-you" },
  { es: "Por favor", en: "Please", category: "yes/no/please/thank-you" },
  { es: "Gracias", en: "Thank you", category: "yes/no/please/thank-you" },
  { es: "Muchas gracias", en: "Thank you very much", category: "yes/no/please/thank-you" },
  { es: "De nada", en: "You're welcome", category: "yes/no/please/thank-you" },
  { es: "Con mucho gusto", en: "My pleasure", category: "yes/no/please/thank-you" },
  { es: "Claro que sí", en: "Of course", category: "yes/no/please/thank-you" },
  { es: "Quizás", en: "Maybe", category: "yes/no/please/thank-you" },
  { es: "Perdón", en: "Excuse me", category: "courtesy" },
  { es: "Disculpe", en: "Excuse me (formal)", category: "courtesy" },
  { es: "Lo siento", en: "I'm sorry", category: "courtesy" },
  { es: "No pasa nada", en: "No problem", category: "courtesy" },
  { es: "Con permiso", en: "Excuse me (passing by)", category: "courtesy" },
  { es: "Es muy amable", en: "That's very kind", category: "courtesy" },
  { es: "No se preocupe", en: "Don't worry", category: "courtesy" },
  { es: "Después de usted", en: "After you", category: "courtesy" },
  { es: "Adiós", en: "Goodbye", category: "goodbyes" },
  { es: "Hasta luego", en: "See you later", category: "goodbyes" },
  { es: "Hasta mañana", en: "See you tomorrow", category: "goodbyes" },
  { es: "Hasta pronto", en: "See you soon", category: "goodbyes" },
  { es: "Nos vemos", en: "See you", category: "goodbyes" },
  { es: "Que tengas un buen día", en: "Have a good day", category: "goodbyes" },
  { es: "Buen viaje", en: "Have a good trip", category: "goodbyes" },
  { es: "Cuídate", en: "Take care", category: "goodbyes" },
  { es: "¿Hablas inglés?", en: "Do you speak English?", category: "small talk" },
  { es: "No hablo español", en: "I don't speak Spanish", category: "small talk" },
  { es: "Hablo un poco", en: "I speak a little", category: "small talk" },
  { es: "No entiendo", en: "I don't understand", category: "small talk" },
  { es: "¿Puedes repetir?", en: "Can you repeat that?", category: "small talk" },
  { es: "Más despacio, por favor", en: "Slower, please", category: "small talk" },
  { es: "Hace buen tiempo", en: "The weather is nice", category: "small talk" },
  { es: "¿Qué haces?", en: "What do you do?", category: "small talk" },
  { es: "Me gusta mucho", en: "I like it a lot", category: "small talk" },
  { es: "Una mesa para dos, por favor.", en: "A table for two, please.", category: "restaurants" },
  { es: "¿Tienen una reserva?", en: "Do you have a reservation?", category: "restaurants" },
  { es: "La carta, por favor.", en: "The menu, please.", category: "menu" },
  { es: "¿Me trae el menú?", en: "Can you bring me the menu?", category: "menu" },
  { es: "¿Qué me recomienda?", en: "What do you recommend?", category: "ordering" },
  { es: "¿Cuál es el plato del día?", en: "What is the dish of the day?", category: "menu" },
  { es: "Quisiera pedir.", en: "I would like to order.", category: "ordering" },
  { es: "Para mí, la sopa.", en: "For me, the soup.", category: "ordering" },
  { es: "Quiero una hamburguesa.", en: "I want a hamburger.", category: "ordering" },
  { es: "Sin cebolla, por favor.", en: "No onion, please.", category: "ordering" },
  { es: "¿Tienen menú del día?", en: "Do you have a set menu?", category: "menu" },
  { es: "¿Qué hay de postre?", en: "What is there for dessert?", category: "menu" },
  { es: "Una botella de agua.", en: "A bottle of water.", category: "drink" },
  { es: "Agua con gas, por favor.", en: "Sparkling water, please.", category: "drink" },
  { es: "Agua sin gas.", en: "Still water.", category: "drink" },
  { es: "Un café, por favor.", en: "A coffee, please.", category: "cafe" },
  { es: "Un café con leche.", en: "A coffee with milk.", category: "cafe" },
  { es: "Un café solo.", en: "A black coffee.", category: "cafe" },
  { es: "Un té, por favor.", en: "A tea, please.", category: "cafe" },
  { es: "Una cerveza, por favor.", en: "A beer, please.", category: "drink" },
  { es: "Una copa de vino tinto.", en: "A glass of red wine.", category: "drink" },
  { es: "Un vaso de vino blanco.", en: "A glass of white wine.", category: "drink" },
  { es: "Un zumo de naranja.", en: "An orange juice.", category: "drink" },
  { es: "¿Tienen vino de la casa?", en: "Do you have house wine?", category: "drink" },
  { es: "Para empezar.", en: "To start.", category: "ordering" },
  { es: "De primer plato.", en: "For the first course.", category: "ordering" },
  { es: "De segundo plato.", en: "For the main course.", category: "ordering" },
  { es: "Eso es todo, gracias.", en: "That is all, thank you.", category: "ordering" },
  { es: "¿Qué lleva este plato?", en: "What is in this dish?", category: "menu" },
  { es: "¿Está picante?", en: "Is it spicy?", category: "menu" },
  { es: "No muy picante, por favor.", en: "Not too spicy, please.", category: "ordering" },
  { es: "Soy vegetariano.", en: "I am vegetarian.", category: "dietary" },
  { es: "Soy vegana.", en: "I am vegan.", category: "dietary" },
  { es: "Soy alérgico a los frutos secos.", en: "I am allergic to nuts.", category: "dietary" },
  { es: "Soy alérgica al marisco.", en: "I am allergic to shellfish.", category: "dietary" },
  { es: "No puedo comer gluten.", en: "I cannot eat gluten.", category: "dietary" },
  { es: "¿Tienen opciones sin gluten?", en: "Do you have gluten-free options?", category: "dietary" },
  { es: "¿Lleva lácteos?", en: "Does it have dairy?", category: "dietary" },
  { es: "Sin sal, por favor.", en: "Without salt, please.", category: "dietary" },
  { es: "¿Tienen platos vegetarianos?", en: "Do you have vegetarian dishes?", category: "dietary" },
  { es: "¿Qué lleva esta salsa?", en: "What is in this sauce?", category: "menu" },
  { es: "Poco hecho, por favor.", en: "Rare, please.", category: "ordering" },
  { es: "Bien hecho, por favor.", en: "Well done, please.", category: "ordering" },
  { es: "Está muy rico.", en: "It is very tasty.", category: "restaurants" },
  { es: "¿Me trae más pan?", en: "Can you bring more bread?", category: "ordering" },
  { es: "¿Me trae una servilleta?", en: "Can you bring a napkin?", category: "restaurants" },
  { es: "Falta un tenedor.", en: "A fork is missing.", category: "restaurants" },
  { es: "La cuenta, por favor.", en: "The check, please.", category: "check" },
  { es: "¿Me trae la cuenta?", en: "Can you bring the check?", category: "check" },
  { es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?", category: "check" },
  { es: "¿Aceptan tarjeta de crédito?", en: "Do you accept credit cards?", category: "check" },
  { es: "Pago en efectivo.", en: "I will pay in cash.", category: "check" },
  { es: "¿Está incluida la propina?", en: "Is the tip included?", category: "check" },
  { es: "Creo que hay un error.", en: "I think there is a mistake.", category: "check" },
  { es: "¿Pueden separar la cuenta?", en: "Can you split the check?", category: "check" },
  { es: "Para llevar, por favor.", en: "To go, please.", category: "ordering" },
  { es: "¿Tienen mesa fuera?", en: "Do you have a table outside?", category: "restaurants" },
  { es: "¿Dónde está el baño?", en: "Where is the bathroom?", category: "directions" },
  { es: "¿Cómo llego al centro?", en: "How do I get to downtown?", category: "directions" },
  { es: "Estoy perdido.", en: "I am lost.", category: "directions" },
  { es: "Estoy perdida.", en: "I am lost.", category: "directions" },
  { es: "¿Me puede ayudar?", en: "Can you help me?", category: "directions" },
  { es: "Gire a la derecha.", en: "Turn right.", category: "directions" },
  { es: "Gire a la izquierda.", en: "Turn left.", category: "directions" },
  { es: "Siga derecho.", en: "Go straight ahead.", category: "directions" },
  { es: "Siga recto.", en: "Keep going straight.", category: "directions" },
  { es: "A la derecha", en: "To the right", category: "directions" },
  { es: "A la izquierda", en: "To the left", category: "directions" },
  { es: "Todo recto", en: "Straight ahead", category: "directions" },
  { es: "Está cerca.", en: "It is near.", category: "directions" },
  { es: "Está lejos.", en: "It is far.", category: "directions" },
  { es: "¿Está lejos?", en: "Is it far?", category: "directions" },
  { es: "¿Está cerca de aquí?", en: "Is it near here?", category: "directions" },
  { es: "¿Dónde estamos?", en: "Where are we?", category: "directions" },
  { es: "¿Dónde está la estación?", en: "Where is the station?", category: "directions" },
  { es: "¿Dónde está el hotel?", en: "Where is the hotel?", category: "directions" },
  { es: "¿Dónde está el banco?", en: "Where is the bank?", category: "directions" },
  { es: "¿Dónde está el museo?", en: "Where is the museum?", category: "directions" },
  { es: "¿Dónde está la plaza?", en: "Where is the square?", category: "directions" },
  { es: "¿Dónde está la playa?", en: "Where is the beach?", category: "directions" },
  { es: "¿Dónde está el aeropuerto?", en: "Where is the airport?", category: "directions" },
  { es: "¿Dónde está la entrada?", en: "Where is the entrance?", category: "directions" },
  { es: "En la esquina", en: "On the corner", category: "directions" },
  { es: "Al final de la calle", en: "At the end of the street", category: "directions" },
  { es: "Cruce la calle.", en: "Cross the street.", category: "directions" },
  { es: "Al lado del banco", en: "Next to the bank", category: "directions" },
  { es: "Enfrente de la iglesia", en: "Across from the church", category: "directions" },
  { es: "Detrás del hotel", en: "Behind the hotel", category: "directions" },
  { es: "Cerca de la plaza", en: "Near the square", category: "directions" },
  { es: "La primera calle", en: "The first street", category: "directions" },
  { es: "La segunda a la derecha", en: "The second on the right", category: "directions" },
  { es: "Dos cuadras más", en: "Two more blocks", category: "directions" },
  { es: "¿Cuántas cuadras?", en: "How many blocks?", category: "directions" },
  { es: "¿A cuánto está?", en: "How far is it?", category: "directions" },
  { es: "¿Se puede ir caminando?", en: "Can I walk there?", category: "directions" },
  { es: "¿Está a pie?", en: "Is it walkable?", category: "directions" },
  { es: "¿Por dónde?", en: "Which way?", category: "directions" },
  { es: "¿Por aquí?", en: "This way?", category: "directions" },
  { es: "Por allí", en: "Over there", category: "directions" },
  { es: "Aquí mismo", en: "Right here", category: "directions" },
  { es: "¿Me puede mostrar en el mapa?", en: "Can you show me on the map?", category: "directions" },
  { es: "Estoy buscando esta dirección.", en: "I am looking for this address.", category: "directions" },
  { es: "¿Cómo se llama esta calle?", en: "What is this street called?", category: "directions" },
  { es: "Creo que me equivoqué de camino.", en: "I think I took the wrong way.", category: "directions" },
  { es: "No conozco esta zona.", en: "I do not know this area.", category: "directions" },
  { es: "¿Puede repetir, por favor?", en: "Can you repeat that, please?", category: "directions" },
  { es: "Más despacio, por favor.", en: "Slower, please.", category: "directions" },
  { es: "Tengo una reserva.", en: "I have a reservation.", category: "reservations" },
  { es: "¿Tiene habitaciones libres?", en: "Do you have any rooms available?", category: "reservations" },
  { es: "Quisiera reservar una habitación.", en: "I would like to book a room.", category: "reservations" },
  { es: "Una habitación doble, por favor.", en: "A double room, please.", category: "reservations" },
  { es: "Una habitación individual.", en: "A single room.", category: "reservations" },
  { es: "¿Cuánto cuesta por noche?", en: "How much is it per night?", category: "reservations" },
  { es: "Para dos noches.", en: "For two nights.", category: "reservations" },
  { es: "¿Incluye el desayuno?", en: "Is breakfast included?", category: "reservations" },
  { es: "Quiero cancelar mi reserva.", en: "I want to cancel my reservation.", category: "reservations" },
  { es: "Reservé en línea.", en: "I booked online.", category: "reservations" },
  { es: "Quisiera registrarme.", en: "I would like to check in.", category: "checking in" },
  { es: "La reserva está a nombre de García.", en: "The reservation is under Garcia.", category: "checking in" },
  { es: "Aquí tiene mi pasaporte.", en: "Here is my passport.", category: "checking in" },
  { es: "¿A qué hora es el registro?", en: "What time is check-in?", category: "checking in" },
  { es: "¿Puedo dejar las maletas?", en: "Can I leave my bags?", category: "checking in" },
  { es: "¿Me da la llave?", en: "May I have the key?", category: "checking in" },
  { es: "¿En qué piso está?", en: "What floor is it on?", category: "checking in" },
  { es: "Llegaré tarde.", en: "I will arrive late.", category: "checking in" },
  { es: "¿Dónde está el ascensor?", en: "Where is the elevator?", category: "the room" },
  { es: "La habitación tiene buena vista.", en: "The room has a nice view.", category: "the room" },
  { es: "¿La habitación tiene aire acondicionado?", en: "Does the room have air conditioning?", category: "the room" },
  { es: "Necesito más toallas.", en: "I need more towels.", category: "the room" },
  { es: "¿Puede limpiar la habitación?", en: "Can you clean the room?", category: "the room" },
  { es: "La cama es muy cómoda.", en: "The bed is very comfortable.", category: "the room" },
  { es: "¿Dónde está el enchufe?", en: "Where is the outlet?", category: "the room" },
  { es: "Quisiera una habitación más tranquila.", en: "I would like a quieter room.", category: "the room" },
  { es: "¿Hay wifi gratis?", en: "Is there free wifi?", category: "amenities" },
  { es: "¿Cuál es la contraseña del wifi?", en: "What is the wifi password?", category: "amenities" },
  { es: "¿Tienen piscina?", en: "Do you have a pool?", category: "amenities" },
  { es: "¿Dónde está el gimnasio?", en: "Where is the gym?", category: "amenities" },
  { es: "¿Hay servicio de habitaciones?", en: "Is there room service?", category: "amenities" },
  { es: "¿A qué hora abre el desayuno?", en: "What time does breakfast open?", category: "amenities" },
  { es: "¿Tienen estacionamiento?", en: "Do you have parking?", category: "amenities" },
  { es: "¿Hay caja fuerte en la habitación?", en: "Is there a safe in the room?", category: "amenities" },
  { es: "¿Tienen servicio de lavandería?", en: "Do you have laundry service?", category: "amenities" },
  { es: "El aire acondicionado no funciona.", en: "The air conditioning is not working.", category: "problems" },
  { es: "No hay agua caliente.", en: "There is no hot water.", category: "problems" },
  { es: "La habitación está muy fría.", en: "The room is very cold.", category: "problems" },
  { es: "El baño está sucio.", en: "The bathroom is dirty.", category: "problems" },
  { es: "La llave no funciona.", en: "The key is not working.", category: "problems" },
  { es: "Hay mucho ruido.", en: "There is a lot of noise.", category: "problems" },
  { es: "El inodoro está atascado.", en: "The toilet is clogged.", category: "problems" },
  { es: "La luz no enciende.", en: "The light will not turn on.", category: "problems" },
  { es: "Quisiera cambiar de habitación.", en: "I would like to change rooms.", category: "problems" },
  { es: "Quisiera hacer el checkout.", en: "I would like to check out.", category: "checkout" },
  { es: "¿A qué hora es la salida?", en: "What time is checkout?", category: "checkout" },
  { es: "¿Puedo salir más tarde?", en: "Can I have a late checkout?", category: "checkout" },
  { es: "¿Me da la factura, por favor?", en: "May I have the bill, please?", category: "checkout" },
  { es: "Creo que hay un error en la cuenta.", en: "I think there is an error on the bill.", category: "checkout" },
  { es: "¿Pueden guardar mi equipaje?", en: "Can you hold my luggage?", category: "checkout" },
  { es: "¿Cuánto cuesta?", en: "How much is it?", category: "shopping and money" },
  { es: "¿Cuánto cuestan?", en: "How much are they?", category: "shopping and money" },
  { es: "Es muy caro.", en: "It's very expensive.", category: "shopping and money" },
  { es: "Es muy barato.", en: "It's very cheap.", category: "shopping and money" },
  { es: "¿Puede bajar el precio?", en: "Can you lower the price?", category: "shopping and money" },
  { es: "¿Me hace un descuento?", en: "Can you give me a discount?", category: "shopping and money" },
  { es: "Es demasiado.", en: "That's too much.", category: "shopping and money" },
  { es: "Le doy diez euros.", en: "I'll give you ten euros.", category: "shopping and money" },
  { es: "¿Acepta tarjeta?", en: "Do you accept card?", category: "shopping and money" },
  { es: "¿Puedo pagar en efectivo?", en: "Can I pay in cash?", category: "shopping and money" },
  { es: "Solo tengo efectivo.", en: "I only have cash.", category: "shopping and money" },
  { es: "¿Dónde está el cajero?", en: "Where is the ATM?", category: "shopping and money" },
  { es: "Quiero pagar, por favor.", en: "I'd like to pay, please.", category: "shopping and money" },
  { es: "¿Cuánto es en total?", en: "How much is it in total?", category: "shopping and money" },
  { es: "¿Tiene cambio?", en: "Do you have change?", category: "shopping and money" },
  { es: "Quédese con el cambio.", en: "Keep the change.", category: "shopping and money" },
  { es: "Me llevo este.", en: "I'll take this one.", category: "shopping and money" },
  { es: "Solo estoy mirando.", en: "I'm just looking.", category: "shopping and money" },
  { es: "¿Me lo puede mostrar?", en: "Can you show it to me?", category: "shopping and money" },
  { es: "¿Lo tiene en otro color?", en: "Do you have it in another color?", category: "shopping and money" },
  { es: "¿Lo tiene en azul?", en: "Do you have it in blue?", category: "shopping and money" },
  { es: "Lo quiero en rojo.", en: "I want it in red.", category: "shopping and money" },
  { es: "¿Qué talla es?", en: "What size is it?", category: "shopping and money" },
  { es: "¿Tiene una talla más grande?", en: "Do you have a bigger size?", category: "shopping and money" },
  { es: "¿Tiene una talla más pequeña?", en: "Do you have a smaller size?", category: "shopping and money" },
  { es: "Me queda pequeño.", en: "It's too small for me.", category: "shopping and money" },
  { es: "Me queda grande.", en: "It's too big for me.", category: "shopping and money" },
  { es: "¿Me lo puedo probar?", en: "Can I try it on?", category: "shopping and money" },
  { es: "¿Dónde está el probador?", en: "Where is the fitting room?", category: "shopping and money" },
  { es: "¿Está en oferta?", en: "Is it on sale?", category: "shopping and money" },
  { es: "¿Hay rebajas?", en: "Are there any sales?", category: "shopping and money" },
  { es: "¿Cuánto vale esto?", en: "How much is this worth?", category: "shopping and money" },
  { es: "¿Me da una bolsa?", en: "Can I have a bag?", category: "shopping and money" },
  { es: "¿Puede envolverlo?", en: "Can you wrap it?", category: "shopping and money" },
  { es: "¿Dónde está el mercado?", en: "Where is the market?", category: "shopping and money" },
  { es: "¿Dónde está la caja?", en: "Where is the checkout?", category: "shopping and money" },
  { es: "¿Tiene un recibo?", en: "Do you have a receipt?", category: "shopping and money" },
  { es: "¿Me da el recibo?", en: "Can I have the receipt?", category: "shopping and money" },
  { es: "Quiero comprar esto.", en: "I want to buy this.", category: "shopping and money" },
  { es: "No lo quiero, gracias.", en: "I don't want it, thanks.", category: "shopping and money" },
  { es: "¿Puedo pagar con dólares?", en: "Can I pay in dollars?", category: "shopping and money" },
  { es: "¿Cuál es el precio?", en: "What's the price?", category: "shopping and money" },
  { es: "Es un buen precio.", en: "It's a good price.", category: "shopping and money" },
  { es: "¿Me lo deja más barato?", en: "Can you make it cheaper?", category: "shopping and money" },
  { es: "Voy a pensarlo.", en: "I'll think about it.", category: "shopping and money" },
  { es: "¿Aceptan propinas?", en: "Do you accept tips?", category: "shopping and money" },
  { es: "¿Dónde puedo cambiar dinero?", en: "Where can I exchange money?", category: "shopping and money" },
  { es: "¿Cuál es la tasa de cambio?", en: "What's the exchange rate?", category: "shopping and money" },
  { es: "Me quedo con dos.", en: "I'll take two.", category: "shopping and money" },
  { es: "¿Dónde está la estación de tren?", en: "Where is the train station?", category: "transport" },
  { es: "Un billete a Madrid, por favor.", en: "A ticket to Madrid, please.", category: "transport" },
  { es: "¿Cuánto cuesta el billete?", en: "How much is the ticket?", category: "transport" },
  { es: "ida y vuelta", en: "round trip", category: "transport" },
  { es: "solo ida", en: "one way", category: "transport" },
  { es: "¿A qué hora sale el tren?", en: "What time does the train leave?", category: "transport" },
  { es: "¿A qué hora llega el autobús?", en: "What time does the bus arrive?", category: "transport" },
  { es: "¿Dónde puedo comprar billetes?", en: "Where can I buy tickets?", category: "transport" },
  { es: "¿Este autobús va al centro?", en: "Does this bus go downtown?", category: "transport" },
  { es: "¿Para en esta parada?", en: "Does it stop at this stop?", category: "transport" },
  { es: "¿Cuál es mi parada?", en: "Which is my stop?", category: "transport" },
  { es: "Me bajo aquí.", en: "I get off here.", category: "transport" },
  { es: "¿Dónde está la parada de autobús?", en: "Where is the bus stop?", category: "transport" },
  { es: "¿De qué andén sale?", en: "Which platform does it leave from?", category: "transport" },
  { es: "¿En qué andén estamos?", en: "Which platform are we on?", category: "transport" },
  { es: "Necesito un taxi.", en: "I need a taxi.", category: "transport" },
  { es: "Al aeropuerto, por favor.", en: "To the airport, please.", category: "transport" },
  { es: "¿Cuánto cuesta hasta el centro?", en: "How much to downtown?", category: "transport" },
  { es: "Pare aquí, por favor.", en: "Stop here, please.", category: "transport" },
  { es: "¿Puede llevarme a esta dirección?", en: "Can you take me to this address?", category: "transport" },
  { es: "¿Está libre?", en: "Are you available?", category: "transport" },
  { es: "Tengo prisa.", en: "I'm in a hurry.", category: "transport" },
  { es: "¿Hay wifi en el tren?", en: "Is there wifi on the train?", category: "transport" },
  { es: "¿Cuál es el horario?", en: "What is the schedule?", category: "transport" },
  { es: "El tren está retrasado.", en: "The train is delayed.", category: "transport" },
  { es: "Perdí mi tren.", en: "I missed my train.", category: "transport" },
  { es: "¿Dónde hago el transbordo?", en: "Where do I transfer?", category: "transport" },
  { es: "¿Tengo que cambiar de tren?", en: "Do I have to change trains?", category: "transport" },
  { es: "¿Cada cuánto pasa el autobús?", en: "How often does the bus come?", category: "transport" },
  { es: "¿Está ocupado este asiento?", en: "Is this seat taken?", category: "transport" },
  { es: "Este es mi asiento.", en: "This is my seat.", category: "transport" },
  { es: "¿Dónde está la puerta de embarque?", en: "Where is the boarding gate?", category: "transport" },
  { es: "¿A qué hora es el embarque?", en: "What time is boarding?", category: "transport" },
  { es: "¿Dónde recojo el equipaje?", en: "Where do I pick up my luggage?", category: "transport" },
  { es: "Mi vuelo está retrasado.", en: "My flight is delayed.", category: "transport" },
  { es: "Mi vuelo fue cancelado.", en: "My flight was canceled.", category: "transport" },
  { es: "¿Dónde está la facturación?", en: "Where is check-in?", category: "transport" },
  { es: "¿Dónde está el control de seguridad?", en: "Where is security?", category: "transport" },
  { es: "¿Puerta cuántos?", en: "Which gate?", category: "transport" },
  { es: "He perdido el vuelo.", en: "I missed my flight.", category: "transport" },
  { es: "¿Dónde está la salida?", en: "Where is the exit?", category: "transport" },
  { es: "¿Cuánto tarda el viaje?", en: "How long is the trip?", category: "transport" },
  { es: "¿Es directo?", en: "Is it direct?", category: "transport" },
  { es: "¿Dónde está el metro?", en: "Where is the subway?", category: "transport" },
  { es: "¿Esta es la línea correcta?", en: "Is this the right line?", category: "transport" },
  { es: "¿Hacia dónde va este tren?", en: "Where is this train going?", category: "transport" },
  { es: "Quiero alquilar un coche.", en: "I want to rent a car.", category: "transport" },
  { es: "¿Dónde está la oficina de información?", en: "Where is the information desk?", category: "transport" },
  { es: "Llego tarde.", en: "I'm running late.", category: "transport" },
  { es: "¿Próxima parada?", en: "Next stop?", category: "transport" },
  { es: "Suba, por favor.", en: "Get on, please.", category: "transport" },
  { es: "¿Me puede avisar cuando lleguemos?", en: "Can you tell me when we arrive?", category: "transport" },
  { es: "Buen viaje.", en: "Have a good trip.", category: "transport" },
  { es: "¿Dónde está la farmacia?", en: "Where is the pharmacy?", category: "health and emergencies" },
  { es: "Necesito un médico.", en: "I need a doctor.", category: "health and emergencies" },
  { es: "¡Ayuda!", en: "Help!", category: "health and emergencies" },
  { es: "Llame a la policía.", en: "Call the police.", category: "health and emergencies" },
  { es: "Es una emergencia.", en: "It's an emergency.", category: "health and emergencies" },
  { es: "Me duele la cabeza.", en: "My head hurts.", category: "health and emergencies" },
  { es: "Me duele el estómago.", en: "My stomach hurts.", category: "health and emergencies" },
  { es: "Estoy enfermo.", en: "I am sick.", category: "health and emergencies" },
  { es: "Llame a una ambulancia.", en: "Call an ambulance.", category: "health and emergencies" },
  { es: "Soy alérgica a la penicilina.", en: "I am allergic to penicillin.", category: "health and emergencies" },
  { es: "Necesito esta medicina.", en: "I need this medicine.", category: "health and emergencies" },
  { es: "¿Tiene algo para el dolor?", en: "Do you have something for pain?", category: "health and emergencies" },
  { es: "Me siento mareado.", en: "I feel dizzy.", category: "health and emergencies" },
  { es: "Tengo fiebre.", en: "I have a fever.", category: "health and emergencies" },
  { es: "He perdido mi pasaporte.", en: "I lost my passport.", category: "health and emergencies" },
  { es: "Perdí mi cartera.", en: "I lost my wallet.", category: "health and emergencies" },
  { es: "Me robaron el bolso.", en: "My bag was stolen.", category: "health and emergencies" },
  { es: "¿Dónde está el hospital?", en: "Where is the hospital?", category: "health and emergencies" },
  { es: "Necesito ayuda.", en: "I need help.", category: "health and emergencies" },
  { es: "¿Puede ayudarme?", en: "Can you help me?", category: "health and emergencies" },
  { es: "Me duele aquí.", en: "It hurts here.", category: "health and emergencies" },
  { es: "No me siento bien.", en: "I don't feel well.", category: "health and emergencies" },
  { es: "Tengo dolor de muelas.", en: "I have a toothache.", category: "health and emergencies" },
  { es: "¿Necesito receta?", en: "Do I need a prescription?", category: "health and emergencies" },
  { es: "Tengo una alergia.", en: "I have an allergy.", category: "health and emergencies" },
  { es: "Estoy embarazada.", en: "I am pregnant.", category: "health and emergencies" },
  { es: "Soy diabético.", en: "I am diabetic.", category: "health and emergencies" },
  { es: "Tengo asma.", en: "I have asthma.", category: "health and emergencies" },
  { es: "No puedo respirar.", en: "I can't breathe.", category: "health and emergencies" },
  { es: "Me corté.", en: "I cut myself.", category: "health and emergencies" },
  { es: "Me caí.", en: "I fell down.", category: "health and emergencies" },
  { es: "Me duele la garganta.", en: "My throat hurts.", category: "health and emergencies" },
  { es: "Tengo tos.", en: "I have a cough.", category: "health and emergencies" },
  { es: "Necesito un dentista.", en: "I need a dentist.", category: "health and emergencies" },
  { es: "¿Hay una farmacia cerca?", en: "Is there a pharmacy nearby?", category: "health and emergencies" },
  { es: "Llame a un médico, por favor.", en: "Call a doctor, please.", category: "health and emergencies" },
  { es: "¿Dónde está la comisaría?", en: "Where is the police station?", category: "health and emergencies" },
  { es: "Quiero denunciar un robo.", en: "I want to report a theft.", category: "health and emergencies" },
  { es: "Perdí mi teléfono.", en: "I lost my phone.", category: "health and emergencies" },
  { es: "Perdí mis llaves.", en: "I lost my keys.", category: "health and emergencies" },
  { es: "Tengo náuseas.", en: "I feel nauseous.", category: "health and emergencies" },
  { es: "Me duele la espalda.", en: "My back hurts.", category: "health and emergencies" },
  { es: "Necesito una farmacia de guardia.", en: "I need a 24-hour pharmacy.", category: "health and emergencies" },
  { es: "Estoy herido.", en: "I am injured.", category: "health and emergencies" },
  { es: "¿Cuánto cuesta esta medicina?", en: "How much is this medicine?", category: "health and emergencies" },
  { es: "Tome esto dos veces al día.", en: "Take this twice a day.", category: "health and emergencies" },
  { es: "Tengo seguro médico.", en: "I have medical insurance.", category: "health and emergencies" },
  { es: "Llame a mi familia.", en: "Call my family.", category: "health and emergencies" },
  { es: "Es urgente.", en: "It's urgent.", category: "health and emergencies" },
  { es: "uno", en: "one", category: "time" },
  { es: "dos", en: "two", category: "time" },
  { es: "tres", en: "three", category: "time" },
  { es: "cuatro", en: "four", category: "time" },
  { es: "cinco", en: "five", category: "time" },
  { es: "seis", en: "six", category: "time" },
  { es: "siete", en: "seven", category: "time" },
  { es: "ocho", en: "eight", category: "time" },
  { es: "nueve", en: "nine", category: "time" },
  { es: "diez", en: "ten", category: "time" },
  { es: "once", en: "eleven", category: "time" },
  { es: "doce", en: "twelve", category: "time" },
  { es: "trece", en: "thirteen", category: "time" },
  { es: "catorce", en: "fourteen", category: "time" },
  { es: "quince", en: "fifteen", category: "time" },
  { es: "dieciséis", en: "sixteen", category: "time" },
  { es: "diecisiete", en: "seventeen", category: "time" },
  { es: "dieciocho", en: "eighteen", category: "time" },
  { es: "diecinueve", en: "nineteen", category: "time" },
  { es: "veinte", en: "twenty", category: "time" },
  { es: "treinta", en: "thirty", category: "time" },
  { es: "cuarenta", en: "forty", category: "time" },
  { es: "cincuenta", en: "fifty", category: "time" },
  { es: "sesenta", en: "sixty", category: "time" },
  { es: "setenta", en: "seventy", category: "time" },
  { es: "ochenta", en: "eighty", category: "time" },
  { es: "noventa", en: "ninety", category: "time" },
  { es: "cien", en: "one hundred", category: "time" },
  { es: "lunes", en: "Monday", category: "time" },
  { es: "martes", en: "Tuesday", category: "time" },
  { es: "miércoles", en: "Wednesday", category: "time" },
  { es: "jueves", en: "Thursday", category: "time" },
  { es: "viernes", en: "Friday", category: "time" },
  { es: "sábado", en: "Saturday", category: "time" },
  { es: "domingo", en: "Sunday", category: "time" },
  { es: "¿Qué hora es?", en: "What time is it?", category: "time" },
  { es: "Es la una.", en: "It's one o'clock.", category: "time" },
  { es: "Son las dos.", en: "It's two o'clock.", category: "time" },
  { es: "Son las tres y media.", en: "It's three thirty.", category: "time" },
  { es: "Son las cuatro y cuarto.", en: "It's a quarter past four.", category: "time" },
  { es: "Son las cinco menos cuarto.", en: "It's a quarter to five.", category: "time" },
  { es: "Son las diez y diez.", en: "It's ten past ten.", category: "time" },
  { es: "el mediodía", en: "noon", category: "time" },
  { es: "la medianoche", en: "midnight", category: "time" },
  { es: "de la mañana", en: "in the morning", category: "time" },
  { es: "de la tarde", en: "in the afternoon", category: "time" },
  { es: "de la noche", en: "at night", category: "time" },
  { es: "¿A qué hora?", en: "At what time?", category: "time" },
  { es: "hoy", en: "today", category: "time" },
  { es: "mañana", en: "tomorrow", category: "time" },
  { es: "ayer", en: "yesterday", category: "time" },
  { es: "pasado mañana", en: "the day after tomorrow", category: "time" },
  { es: "¿Qué día es hoy?", en: "What day is it today?", category: "time" },
  { es: "¿Cuál es la fecha?", en: "What's the date?", category: "time" },
  { es: "esta semana", en: "this week", category: "time" },
  { es: "la próxima semana", en: "next week", category: "time" },
  { es: "ahora mismo", en: "right now", category: "time" },
  { es: "más tarde", en: "later", category: "time" },
  { es: "temprano", en: "early", category: "time" },
  { es: "tarde", en: "late", category: "time" },
];

export default SPANISH_PHRASES;

// END mchatai-web-components: resources.spanish-phrasebook
